#!/bin/bash
# Turns THIS already-provisioned machine into a Cyberbeest live-boot ISO,
# instead of building one from a blank Debian base + first-boot provisioning
# (see ~/claude/live-stick/build-live-stick.sh on the dev machine, and its
# README, for that approach and why it exists). This is the "ideal mode"
# version: locale, installed packages, panel layout, xfconf/gsettings state
# -- all of it just comes along because it's already sitting on disk, no
# reprovisioning needed at boot.
#
# NOT part of the numbered NN-*.sh provisioning sequence (deliberately
# unnumbered so run-gui.py's [0-9][0-9]-*.sh glob never picks it up) --
# this is a one-shot tool you run directly, not a provisioning step.
#
# EXPERIMENTAL, first cut: the sanitization list below (machine-id, SSH host
# keys, saved wifi passwords, LUKS/fstab, ...) covers the obvious
# machine-identity and credential leaks, but has NOT been reviewed
# end-to-end for anything more subtle before this touches a real
# distributed image. Treat the output as a test artifact, not something to
# hand to a customer, until that review happens.
#
# Usage: sudo bash remaster-live-stick.sh
# Run this ON the machine you want snapshotted (e.g. a provisioned test
# unit), as root. Needs a few GB free disk (rsync copy + squashfs + ISO all
# coexist during the build) and modifies nothing on the source system itself
# -- it only reads from / and writes to $WORK below.
set -euo pipefail

DIR="$(cd "$(dirname "$0")" && pwd)"
LOG="$DIR/remaster-live-stick.log"
exec > >(tee -a "$LOG") 2>&1

echo "=== $(date) : starting live-stick remaster ==="

if [ "$(id -u)" -ne 0 ]; then
	echo "Must run as root (sudo bash $0)." >&2
	exit 1
fi

WORK="/root/live-stick-remaster"
CHROOT="$WORK/chroot"

echo "--- Clearing any leftover build state from a previous run ---"
# A prior interrupted/failed run can leave $CHROOT in a half-configured
# state (found 2026-09-04: a stale dpkg-divert from an earlier live-tools
# install collided with the same divert on a later run, since rsync below
# has no --delete and never gets a clean slate otherwise) that then breaks
# apt in ways unrelated to whatever actually caused this run.
#
# A prior run failing (set -e) between the mount --bind calls below and
# their matching umount can leave $CHROOT/{dev,proc,sys} bind-mounted to
# the REAL host directories. Plain `rm -rf` does not stop at mount-point
# boundaries -- it recurses straight through a stale bind mount and
# deletes the host's actual /dev contents (done once already, 2026-09-04,
# wiped the real /dev on a build host and broke sshd). Unmount anything
# still mounted under $CHROOT first, every time, before removing it.
for sub in dev proc sys; do
	mountpoint -q "$CHROOT/$sub" 2>/dev/null && umount "$CHROOT/$sub"
done
rm -rf --one-file-system "$WORK"

echo "--- Installing live-build host toolchain ---"
# Same list build-live-stick.sh needed on the dev machine, discovered one
# failure at a time during that bring-up: --build-with-chroot false (used
# below, since we're populating chroot/ ourselves rather than letting
# live-build debootstrap it) runs mksquashfs and the bootloader-assembly
# tools on the host instead of self-chroot-mounted, so they all need to
# exist here too.
apt-get -o DPkg::Lock::Timeout=60 update
apt-get -o DPkg::Lock::Timeout=60 install -y \
	live-build squashfs-tools dctrl-tools isolinux syslinux-common \
	grub-pc-bin grub-efi-amd64-bin grub-efi-ia32-bin mtools librsvg2-bin \
	xorriso rsync

echo "--- Configuring live-build ---"
mkdir -p "$WORK"
cd "$WORK"
lb config \
	--distribution trixie \
	--architectures amd64 \
	--archive-areas "main contrib non-free non-free-firmware" \
	--debian-installer none \
	--binary-images iso-hybrid \
	--iso-application "Cyberbeest Live" \
	--iso-volume "Cyberbeest Live" \
	--chroot-squashfs-compression-type zstd \
	--build-with-chroot false

echo "--- Copying this machine's root filesystem into $CHROOT ---"
echo "(this reads from / but writes only under $WORK -- nothing on the"
echo "source system is modified)"
mkdir -p "$CHROOT"
rsync -aAX --numeric-ids \
	--exclude="/dev/*" \
	--exclude="/proc/*" \
	--exclude="/sys/*" \
	--exclude="/tmp/*" \
	--exclude="/run/*" \
	--exclude="/mnt/*" \
	--exclude="/media/*" \
	--exclude="/lost+found" \
	--exclude="/swapfile" \
	--exclude="/swap.img" \
	--exclude="$WORK" \
	--exclude="/var/cache/apt/archives/*.deb" \
	/ "$CHROOT"/

echo "--- Sanitizing the copy (machine identity, credentials) ---"
# Machine identity -- regenerated fresh by systemd/dbus on first boot of the
# live image if left empty/absent.
: >"$CHROOT/etc/machine-id"
rm -f "$CHROOT/var/lib/dbus/machine-id"

# SSH host keys -- regenerated by openssh-server's postinst/a systemd
# generator on first boot if absent; shipping the real machine's keys would
# mean every booted stick (and the source machine) shares host identity.
rm -f "$CHROOT"/etc/ssh/ssh_host_*

# SSH keypairs (this machine's own login keys / known_hosts) and saved wifi
# passwords -- both plausible credential leaks if shipped as-is.
rm -rf "$CHROOT"/root/.ssh "$CHROOT"/home/*/.ssh
rm -f "$CHROOT"/etc/NetworkManager/system-connections/*
# (matches both the modern *.nmconnection naming and the older bare-name
# keyfile convention -- found 2026-09-04 that a profile saved under the old
# naming scheme survived the *.nmconnection-only glob and shipped a real
# wifi PSK on a remastered stick)

# Disk-specific config that doesn't apply to a squashfs+overlay live root
# and would otherwise make the live initramfs try to unlock/mount devices
# that don't exist on whatever machine the stick boots on.
: >"$CHROOT/etc/crypttab"
cat >"$CHROOT/etc/fstab" <<-'EOF'
	# Regenerated for the live image -- live-boot handles the actual root
	# mount (squashfs + tmpfs/persistence overlay); this machine's original
	# fstab (real disk UUIDs, LUKS mapper devices) doesn't apply here.
	proc /proc proc defaults 0 0
EOF

# Local-only state that's either bulky or just noise on a fresh boot.
rm -rf "$CHROOT"/var/log/* "$CHROOT"/var/cache/apt/archives/*.deb
rm -f "$CHROOT"/root/.bash_history "$CHROOT"/home/*/.bash_history
rm -rf "$CHROOT"/var/spool/cron/crontabs/* "$CHROOT"/var/mail/* "$CHROOT"/var/spool/mail/*
rm -rf "$CHROOT"/home/*/.cache "$CHROOT"/root/.cache

echo "--- Installing live-boot/live-config into the copied system ---"
# The source machine is a normal installed system, so it has no reason to
# already have these -- without them the squashfs boots but never mounts
# itself as a live root or autologins.
mount --bind /dev "$CHROOT/dev"
mount --bind /proc "$CHROOT/proc"
mount --bind /sys "$CHROOT/sys"
# Guarantee these come back off even if a later command in this script
# fails (set -e exits immediately) -- otherwise the next run's cleanup has
# to deal with a live bind mount to the real host directories instead of
# an ordinary leftover directory.
trap 'umount "$CHROOT/dev" "$CHROOT/proc" "$CHROOT/sys" 2>/dev/null' EXIT
cp /etc/resolv.conf "$CHROOT/etc/resolv.conf"
chroot "$CHROOT" apt-get -o DPkg::Lock::Timeout=60 update
chroot "$CHROOT" apt-get -o DPkg::Lock::Timeout=60 install -y \
	live-boot live-config live-config-systemd

# The donor machine only ever needed its own GPU's firmware (Intel, on the
# dev laptop), so that's all /lib/firmware carries in this copy. A stick
# booted on different graphics hardware then has no firmware to load at all
# -- found 2026-09-03 booting on an AMD-GPU machine ("fatal amd gpu error"
# during KMS init), severe enough to wedge boot before live-config finishes
# creating the autologin "user" account, so every VT loops on the same
# authentication failure instead of just showing a broken display. Installing
# every vendor's firmware package covers whatever GPU/wifi/etc. a given boot
# target has, at the cost of a larger image.
chroot "$CHROOT" apt-get -o DPkg::Lock::Timeout=60 install -y \
	firmware-amd-graphics firmware-misc-nonfree firmware-realtek \
	firmware-iwlwifi firmware-atheros firmware-linux

echo "--- Regenerating initramfs (with crypttab cleared, live-boot hooks added) ---"
# live-build's own binary_linux-image stage just cp's whatever
# chroot/boot/initrd.img-* already exists (see /usr/lib/live/build/
# binary_linux-image) -- it does NOT rebuild it. Left alone, that's still
# the donor machine's real initramfs, built back when /etc/crypttab pointed
# at its actual LUKS UUID -- the cryptsetup hook bakes that UUID into the
# image at generation time, so clearing the crypttab *text file* above does
# nothing to an initramfs that was already compiled before that edit. Result
# (found 2026-08-30 booting the first remastered image): the live system
# hangs at an early-boot LUKS unlock prompt for a device that doesn't exist.
# Rebuilding now, after both edits (crypttab cleared, live-boot installed),
# picks up both fixes in one pass.
chroot "$CHROOT" update-initramfs -u -k all

umount "$CHROOT/dev" "$CHROOT/proc" "$CHROOT/sys"

echo "--- Marking chroot-population stages as already done ---"
# We populated chroot/ ourselves instead of letting live-build debootstrap
# it, so tell it to skip straight past bootstrap + chroot package-install
# stages to the binary-assembly stages (squashfs, bootloader, ISO). These
# are live-build's own internal stage markers (touched by its scripts via
# Set_stagefile; see /usr/lib/live/build/) -- this is the same trick as
# resuming a partial build, just applied to stages we did by hand instead.
mkdir -p .build
for stage in bootstrap chroot_apt chroot_archives chroot_devpts chroot_dpkg \
	chroot_firmware chroot_hacks chroot_hostname chroot_hosts \
	chroot_includes_after_packages chroot_includes_before_packages \
	chroot_install-packages.install chroot_install-packages.live \
	chroot_linux-image chroot_package-lists.install \
	chroot_package-lists.live chroot_preseed chroot_proc chroot_resolv \
	chroot_sysfs chroot_sysv-rc; do
	touch ".build/$stage"
done

echo "--- Building the live image (this takes a while: squashfs of the full system) ---"
lb build

OUT_ISO="$DIR/cyberbeest-live-remastered-amd64.iso"
ISO_FILE="$(find "$WORK" -maxdepth 1 -name '*.iso' | head -1)"
if [ -z "$ISO_FILE" ]; then
	echo "Build finished but no .iso found -- check the log above." >&2
	exit 1
fi
mv "$ISO_FILE" "$OUT_ISO"
chown "${SUDO_USER:-cyberbeest}:${SUDO_USER:-cyberbeest}" "$OUT_ISO"

echo
echo "=== $(date) : done ==="
echo "Image: $OUT_ISO"
ls -lh "$OUT_ISO"
echo "Write it to a stick with:"
echo "  sudo dd if=$OUT_ISO of=/dev/sdX bs=4M status=progress conv=fsync"
