#!/bin/bash
# Panel item: merges update-genmon.sh (security-update status) and
# shutdown-timer-genmon.sh (auto-shutdown-while-locked status) into a single
# xfce4-genmon-plugin instance -- two separate genmon processes cost an
# extra wrapper-process worth of RAM each, on every shipped machine, for
# widgets that are cheap to compute. genmon supports independent click
# regions for the icon (<click>) and the text (<txtclick>), so each widget
# keeps its own click handler.

SELF_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck disable=SC1091
. "$SELF_DIR/update-genmon.sh"
# shellcheck disable=SC1091
. "$SELF_DIR/shutdown-timer-genmon.sh"

# Lock/auto-shutdown first, security-update status second: users check the
# lock-timer far more often than the update status, which they mostly just
# want to trust silently.
lock_heading="<b>$(t panel_status_genmon.lock_heading)</b>"
security_heading="<b>$(t panel_status_genmon.security_heading)</b>"

# First non-loopback address only -- multiple NICs (e.g. a VPN tunnel) would
# otherwise clutter the tooltip with addresses users didn't ask about.
ip_addr="$(hostname -I 2>/dev/null | awk '{print $1}')"
[ -n "$ip_addr" ] || ip_addr="$(t panel_status_genmon.ip_unknown)"
ip_line="$(t panel_status_genmon.ip_line)"
ip_line="${ip_line//ADDR/$ip_addr}"

# Sockets bound to loopback (or an IPv6 link-local address, which is only
# reachable from the same physical segment, never routed) can't be reached
# over the network regardless of firewall state, so they're not worth
# alarming a user about -- only list what's actually exposed.
#
# Whether a non-loopback listening socket is *actually* exposed further
# depends on 63-firewall.sh's default-deny-inbound firewall (if that's
# even installed and active -- e.g. not yet the case on a machine that
# predates it). When it's active, only the ports it explicitly lets
# through can really be reached, so cross-reference against
# /etc/cyberbeest/firewall-allowed-ports (a "proto port name" listing
# generated by that same script from the exact rules it applies -- see
# its own comment for why the tooltip reads a generated file instead of
# querying the live nft ruleset, which needs root). Without an active
# firewall, everything listening on a non-loopback address really is
# reachable, so fall back to showing all of it, same as before this
# firewall existed.
declare -A _known_port_names=(
	[22]="SSH"
	[80]="HTTP"
	[443]="HTTPS"
	[5353]="mDNS"
)
firewall_active=false
systemctl is-active --quiet nftables.service 2>/dev/null && firewall_active=true

declare -A _allowed_ports=()
allowed_ports_file=/etc/cyberbeest/firewall-allowed-ports
if [ "$firewall_active" = true ] && [ -r "$allowed_ports_file" ]; then
	while read -r a_proto a_port a_name; do
		[ -n "$a_proto" ] || continue
		_allowed_ports["${a_proto}:${a_port}"]="$a_name"
	done < "$allowed_ports_file"
fi

declare -A _seen_ports=()
_open_ports=()
while read -r proto local_addr; do
	port="${local_addr##*:}"
	addr="${local_addr%:*}"
	addr="${addr%%\%*}"
	addr="${addr#\[}"
	addr="${addr%\]}"
	case "$addr" in
		127.*|::1|fe80:*|"") continue ;;
	esac
	# With an active firewall, a listening socket the ruleset doesn't
	# admit isn't actually reachable -- don't show it as if it were.
	if [ "$firewall_active" = true ] && [ ${#_allowed_ports[@]} -gt 0 ] \
		&& [ -z "${_allowed_ports[${proto}:${port}]+x}" ]; then
		continue
	fi
	key="${proto}:${port}"
	[ -n "${_seen_ports[$key]+x}" ] && continue
	_seen_ports[$key]=1
	_open_ports+=("$key")
done < <(ss -tulnH 2>/dev/null | awk '{print $1, $5}')

# Numeric order puts SSH (the port people actually check for) right after
# the IP address instead of wherever ss happened to list it.
ports_value=""
while read -r key; do
	proto="${key%%:*}"
	port="${key##*:}"
	name="${_allowed_ports[$key]:-${_known_port_names[$port]:-}}"
	entry="${name:+$name (}${port}${name:+)}"
	ports_value="${ports_value:+$ports_value, }$entry"
done < <(printf '%s\n' "${_open_ports[@]}" | sort -t: -k2 -n)
[ -n "$ports_value" ] || ports_value="$(t panel_status_genmon.ports_none)"
ports_line="$(t panel_status_genmon.ports_line)"
ports_line="${ports_line//PORTS/$ports_value}"

echo "<img>${SECURITY_STATUS_IMG}</img>"
echo "<txt>${SHUTDOWN_TIMER_TXT}</txt>"
echo "<tool>${ip_line}&#10;${ports_line}&#10;&#10;${lock_heading}&#10;${SHUTDOWN_TIMER_TOOL}&#10;&#10;${security_heading}&#10;${SECURITY_STATUS_TOOL}</tool>"
echo "<click>${SECURITY_STATUS_CLICK}</click>"
echo "<txtclick>${SHUTDOWN_TIMER_TXTCLICK}</txtclick>"
